const {chromium}=require(process.env.PLAYWRIGHT_MODULE || 'playwright');
const assert=require('node:assert/strict');
const fs=require('node:fs');
const path=require('node:path');
const output=process.env.UI_ARTIFACT_DIR || path.resolve('artifacts');
(async()=>{
 fs.mkdirSync(output,{recursive:true});
 const browser=await chromium.launch({executablePath:process.env.CHROMIUM_PATH,headless:true,args:['--no-sandbox']});
 try {
  const page=await browser.newPage({viewport:{width:1440,height:1000}});
  const errors=[];const requests=[];page.on('pageerror',e=>errors.push(String(e)));page.on('request',r=>requests.push({method:r.method(),url:r.url()}));
  await page.goto('http://127.0.0.1:19975/ui');
  await page.getByText('接続済み',{exact:true}).waitFor();
  await page.getByText('ロード済み・推論未確認',{exact:true}).waitFor();
  assert.equal(requests.filter(r=>r.method==='POST').length,0,'Initial page must perform no mutations');
  assert.equal(await page.locator('img').count(),0,'Model-derived markup must remain text');
  await page.screenshot({path:path.join(output,'embedding-models-desktop.png'),fullPage:true});
  await page.locator('#model-search').fill('reranker');
  const kind=page.getByRole('combobox',{name:'reranker/synthetic のロード種別'});
  assert.equal(await kind.inputValue(),'reranker');
  assert.equal(await page.getByRole('button',{name:'ロード',exact:true}).isDisabled(),true,'Partial download must block load');
  await page.locator('#model-search').fill('');
  await page.locator('#model-search').fill('Qwen3-Embedding-0.6B');
  await page.getByRole('combobox',{name:'Qwen3-Embedding-0.6B のロード種別'}).selectOption('reranker');
  await page.locator('#refresh').click();await page.getByText('接続済み',{exact:true}).waitFor();
  assert.equal(await page.getByRole('combobox',{name:'Qwen3-Embedding-0.6B のロード種別'}).inputValue(),'reranker','Refresh must retain the chosen load type');
  await page.locator('#model-search').fill('');
  await page.setViewportSize({width:390,height:844});
  await page.screenshot({path:path.join(output,'embedding-models-mobile.png'),fullPage:true});
  assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),'Mobile must not overflow');
  await page.setViewportSize({width:1440,height:1000});
  await page.locator('[data-page="catalog"]').click();
  await page.getByText('取得完了・推論未確認',{exact:true}).waitFor();
  await page.screenshot({path:path.join(output,'embedding-catalog-desktop.png'),fullPage:true});
  await page.locator('#jobs details').first().click();
  await page.locator('#refresh').click();await page.getByText('接続済み',{exact:true}).waitFor();
  assert.equal(await page.locator('#jobs details').first().evaluate(n=>n.open),true,'Polling must retain expanded job logs');
  await page.getByText('Hugging Face から取得先を指定',{exact:true}).click();
  await page.locator('#repo-id').fill('invalid');await page.locator('#download-form button').click();
  await page.getByText('リポジトリ ID は owner/repo 形式で入力してください。',{exact:true}).waitFor();
  await page.locator('#repo-id').fill('synthetic/new-model');await page.locator('#local-name').fill('../outside');await page.locator('#download-form button').click();
  await page.locator('#download-validation').filter({hasText:'相対パス'}).waitFor();
  await page.locator('#local-name').fill('synthetic/new-model');await page.locator('#download-form button').click();
  await page.locator('#confirm-dialog').waitFor();await page.getByRole('button',{name:'キャンセル',exact:true}).click();
  assert.equal(requests.filter(r=>r.method==='POST').length,0,'Cancel must not submit');
  await page.locator('#download-form button').click();await page.locator('#confirm-action').click();
  await page.getByText('ダウンロードを開始しました。ジョブ一覧で進捗を確認できます。',{exact:true}).waitFor();
  assert.equal(requests.filter(r=>r.method==='POST'&&r.url.endsWith('/v1/models/download')).length,1);
  await page.locator('[data-page="playground"]').focus();await page.keyboard.press('Enter');
  await page.locator('#test-model').waitFor();assert.equal(await page.locator('#test-model option').count(),1);
  await page.locator('#dimensions').fill('9');await page.locator('#test-button').click();
  await page.locator('#test-validation').filter({hasText:'HTTP 400'}).waitFor();
  await page.locator('#dimensions').fill('');await page.locator('#test-button').click();
  await page.getByText('ベクトル生成が完了しました',{exact:true}).waitFor();
  await page.screenshot({path:path.join(output,'embedding-playground-desktop.png'),fullPage:true});
  await page.setViewportSize({width:390,height:844});await page.screenshot({path:path.join(output,'embedding-playground-mobile.png'),fullPage:true});
  assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));
  await page.locator('[data-page="models"]').click();await page.getByText('推論確認済み（現ロード）',{exact:true}).waitFor();
  await page.getByRole('button',{name:'アンロード',exact:true}).click();await page.locator('#confirm-action').click();
  await page.getByText('モデルをアンロードしました。',{exact:true}).waitFor();
  await page.locator('#model-search').fill('embedding/ruri');await page.getByRole('button',{name:'ロード',exact:true}).click();await page.locator('#confirm-action').click();
  await page.getByText('ロード済み・推論未確認',{exact:true}).waitFor();
  await page.locator('#model-search').fill('Qwen3-Embedding-0.6B');
  await page.route('**/v1/models/load',route=>route.fulfill({status:500,contentType:'application/json',body:'{"detail":"synthetic load error: VRAM unavailable"}'}));
  await page.getByRole('button',{name:'ロード',exact:true}).click();await page.locator('#confirm-action').click();
  await page.locator('#error').filter({hasText:'synthetic load error'}).waitFor();
  await page.locator('#refresh').click();await page.getByText('接続済み',{exact:true}).waitFor();
  assert.ok((await page.locator('#error').textContent()).includes('synthetic load error'),'Refresh must retain operation errors');
  await page.unroute('**/v1/models/load');
  await page.locator('[data-page="settings"]').click();await page.getByText('実行環境',{exact:true}).waitFor();
  await page.screenshot({path:path.join(output,'embedding-settings-mobile.png'),fullPage:true});
  // The /webui alias and path prefix must preserve every API and asset request.
  await page.goto('http://127.0.0.1:19975/prefix/webui');await page.getByText('接続済み',{exact:true}).waitFor();
  await page.route('**/prefix/health',route=>route.fulfill({status:503,contentType:'application/json',body:'{"detail":"synthetic outage"}'}));
  await page.locator('#refresh').click();await page.getByText('取得失敗・操作停止',{exact:true}).waitFor();
  assert.equal(await page.getByRole('button',{name:'アンロード',exact:true}).isDisabled(),true);
  await page.screenshot({path:path.join(output,'embedding-error-mobile.png'),fullPage:true});
  await page.unroute('**/prefix/health');await page.locator('#refresh').click();await page.getByText('接続済み',{exact:true}).waitFor();
  await page.request.post('http://127.0.0.1:19975/fixture/empty');await page.locator('#refresh').click();
  await page.getByText('ローカルモデルがありません。カタログから取得できます。',{exact:true}).waitFor();
  await page.locator('[data-page="playground"]').click();assert.equal(await page.locator('#test-button').isDisabled(),true);
  await page.screenshot({path:path.join(output,'embedding-empty-mobile.png'),fullPage:true});
  assert.deepEqual(errors,[]);
  fs.writeFileSync(path.join(output,'browser-qa.json'),JSON.stringify({fixture:true,production_inference:false,desktop:'1440x1000',mobile:'390x844',checks:['no implicit mutation','literal model text / XSS','partial download load gate','mobile overflow','download validation / cancellation / single request','retained disclosure and load type on refresh','keyboard navigation','loaded-only playground','400 detail retained','vector summary / cosine','load evidence reset','load error retained on refresh','read-only settings','webui alias / proxy prefix','partial outage action gate / recovery','empty state'],page_errors:errors},null,2));
  console.log('Browser QA passed');
 } finally {await browser.close();}
})().catch(e=>{console.error(e);process.exitCode=1;});
